[project]
name = "assertion"
version = "1.0.0b1"
description = "Supercharged assertion tests"
dependencies = []
requires-python = ">=3.7"
dynamic = []
readme = "README.md"
keywords = [ "assert", "testing",]
classifiers = [ "Topic :: Software Development :: Testing", "Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10",]
[[project.authors]]
name = "COHERENT MINDS Team"
email = "dev@coherentminds.de"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "MIT"

[project.urls]
Repository = "https://gitlab.com/coherentminds/assertion/"
"COHERENT MINDS" = "https://coherentminds.de/"

[tool.black]
line_length = 88

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.pdm.dev-dependencies]
test = [ "pytest~=6.2", "pytest-asyncio~=0.14", "pytest-xdist~=2.2", "hypothesis~=6.3", "pytest-cov~=2.11", "toml~=0.10",]
lint = [ "black~=20.8b1", "isort~=5.7", "mypy~=0.812", "flake8~=3.8",]
deploy = [ "twine~=3.3",]
