[tool.poetry]
name = "response_differ"
version = "0.1.22"
description = ""
authors = ["vkytepov <vkytepov@live.com>"]

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^5.4.1"
requests = "^2.25.1"
deepdiff = "^5.3.0"
click = "^7.1.2"
vcrpy = "^4.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
differ = "response_differ.response_diff.cli:differ"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
