[tool.poetry]
name = "musamusa_atext"
version = "0.0.8"
description = "MusaMusa::AnnotatedText"
authors = ["suizokukan <suizokukan@orange.fr>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.9"
musamusa-errors = "^0.8"
musamusa-textref = "^0.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
