[tool.poetry]
name = "rubixinsights"
version = "0.0.13"
description = "rubixin-sights"
authors = ["rubix"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.1,<4"
boto3 = "1.17.29"
requests = "2.25.1"
PyYAML = "5.3.1"
SQLAlchemy = "1.3.23"
psycopg2-binary = "2.8.6"
pandas = "1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
