[tool.poetry]
name = "devplayer"
version = "0.1.2"
description = "CLI for playing music and creating playlists"
authors = ["Devansh3712 <devanshamity@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
click = "^7.1.2"
colorama = "^0.4.4"
playsound = "^1.2.2"
youtube_dl = "^2021.4.26"
halo = "^0.0.31"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
